timeout: 5000
require:
  - ts-node/register
  - test/setup.js
recursive: true
extension:
  - ts
  - tsx
spec:
  - test/**/*.ts
reporter: list
slow: 500
ignore: __snapshots__
full-trace: true
check-leaks: true
