name: Create GitHub Releases

on:
  push:
    branches:
      - main

jobs:
  create-releases:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Checkout release branch
        run: |
          git config --global user.name "Stainless Bot"
          git config --global user.email "stainless-bot@users.noreply.github.com"
          git checkout release

      - name: Merge main into release branch
        run: |
          git pull origin release --rebase=false --ff-only
          git merge --no-ff main

      - name: Enable corepack
        run: corepack enable

      - uses: actions/setup-node@v6
        with:
          node-version: "24"
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Clean
        run: rm -rf ./build

      - name: Compile
        run: pnpm build

      - name: Commit and push build directory
        run: |
          git add -f ./build
          git diff --cached --exit-code || git commit -m "Build sources"
          git push origin release
